// 1. 显示用户详情 (保持不变)
function showUserDetails(name, email, uid) {
    Swal.fire({
        title: 'User Details',
        html: `
            <div class="text-left">
                <p><strong>Name:</strong> ${name}</p>
                <p><strong>User ID:</strong> ${uid}</p>
                <p><strong>Email:</strong> <a href="mailto:${email}" class="text-blue-600 underline">${email}</a></p>
            </div>
        `,
        icon: 'info'
    });
}

// 2. 新的高级发货逻辑
// 增加第三个参数 rewardType
async function fulfillOrder(recordId, rewardName, rewardType) {
    
    console.log("Fulfilling:", rewardName, "Type:", rewardType); // Debug用

    let formData = new FormData();
    formData.append('record_id', recordId);
    formData.append('update_status', '1'); 

    // === 分流逻辑 ===
    if (rewardType === 'Physical') {
        // [A] 物理奖励 (Tree, Trash bag, etc.) -> 强制要求拍照
        // 这就解决了你的问题：种树是 Physical，所以会走这里
        const { value: file } = await Swal.fire({
            title: 'Physical Proof Required',
            text: `Upload photo proof for "${rewardName}"`,
            input: 'file',
            inputAttributes: { 'accept': 'image/*' },
            showCancelButton: true,
            confirmButtonText: 'Upload & Complete',
            confirmButtonColor: '#10b981'
        });
        if (!file) return; 
        formData.append('proof_photo', file);

    } else {
        // [B] 虚拟奖励 (Virtual) -> 自动发货
        // 这里修复了“点了没反应”的 bug，因为我们不再要求输入 Code，而是直接确认
        const result = await Swal.fire({
            title: 'Issue Virtual Reward?',
            text: `System will auto-generate the code/certificate for "${rewardName}".`,
            icon: 'info',
            showCancelButton: true,
            confirmButtonText: 'Yes, Auto-Issue',
            confirmButtonColor: '#3b82f6'
        });
        
        if (!result.isConfirmed) return;
        formData.append('admin_note', 'Auto-Generated by System');
    }

    // --- 提交 ---
    Swal.fire({ title: 'Processing...', didOpen: () => Swal.showLoading() });

    fetch('Redemption_List.php', { method: 'POST', body: formData })
    .then(response => {
        if(response.ok) {
            Swal.fire('Success', 'Order fulfilled successfully.', 'success')
            .then(() => location.reload());
        } else {
            Swal.fire('Error', 'Server error.', 'error');
        }
    })
    .catch(err => {
        console.error(err);
        Swal.fire('Error', 'Network connection error.', 'error');
    });
}
document.getElementById('searchInput').addEventListener('keyup', function() {
    let filter = this.value.toUpperCase();
    let rows = document.querySelector("tbody").rows;

    for (let i = 0; i < rows.length; i++) {
        // 获取第二列 (User Name) 的文本
        let nameCol = rows[i].cells[1].textContent; 
        if (nameCol.toUpperCase().indexOf(filter) > -1) {
            rows[i].style.display = "";
        } else {
            rows[i].style.display = "none";
        }
    }
});