// 1. Display user details (unchanged)
function showUserDetails(name, email, uid) {
    Swal.fire({
        title: 'User Details',
        html: `
            <div class="text-left">
                <p><strong>Name:</strong> ${name}</p>
                <p><strong>User ID:</strong> ${uid}</p>
                <p><strong>Email:</strong> <a href="mailto:${email}" class="text-blue-600 underline">${email}</a></p>
            </div>
        `,
        icon: 'info'
    });
}

// 2. New advanced fulfillment logic
// Added third parameter rewardType
async function fulfillOrder(recordId, rewardName, rewardType) {
    
    console.log("Fulfilling:", rewardName, "Type:", rewardType); // For debugging

    let formData = new FormData();
    formData.append('record_id', recordId);
    formData.append('update_status', '1'); 

    // === Branching logic ===
    if (rewardType === 'Physical') {
        // [A] Physical rewards (Tree, Trash bag, etc.) -> require photo evidence
        // This fixes your issue: planting trees is Physical, so it goes here
        const { value: file } = await Swal.fire({
            title: 'Physical Proof Required',
            text: `Upload photo proof for "${rewardName}"`,
            input: 'file',
            inputAttributes: { 'accept': 'image/*' },
            showCancelButton: true,
            confirmButtonText: 'Upload & Complete',
            confirmButtonColor: '#10b981'
        });
        if (!file) return; 
        formData.append('proof_photo', file);

    } else {
        // [B] Virtual rewards (Virtual) -> auto-fulfillment
        // Fixed: clicking had no response because we no longer require a code input; we confirm directly
        const result = await Swal.fire({
            title: 'Issue Virtual Reward?',
            text: `System will auto-generate the code/certificate for "${rewardName}".`,
            icon: 'info',
            showCancelButton: true,
            confirmButtonText: 'Yes, Auto-Issue',
            confirmButtonColor: '#3b82f6'
        });
        
        if (!result.isConfirmed) return;
        formData.append('admin_note', 'Auto-Generated by System');
    }

    // --- Submit ---
    Swal.fire({ title: 'Processing...', didOpen: () => Swal.showLoading() });

    fetch('Redemption_List.php', { method: 'POST', body: formData })
    .then(response => {
        if(response.ok) {
            Swal.fire('Success', 'Order fulfilled successfully.', 'success')
            .then(() => location.reload());
        } else {
            Swal.fire('Error', 'Server error.', 'error');
        }
    })
    .catch(err => {
        console.error(err);
        Swal.fire('Error', 'Network connection error.', 'error');
    });
}
document.getElementById('searchInput').addEventListener('keyup', function() {
    let filter = this.value.toUpperCase();
    let rows = document.querySelector("tbody").rows;

    for (let i = 0; i < rows.length; i++) {
        // Get text from the second column (User Name)
        let nameCol = rows[i].cells[1].textContent; 
        if (nameCol.toUpperCase().indexOf(filter) > -1) {
            rows[i].style.display = "";
        } else {
            rows[i].style.display = "none";
        }
    }
});